executor: CharacterBasedExecutor

dataset:
    train: 
      json_path: /kaggle/working/common_voice/dev.json
      voice_path: /kaggle/working/common_voice/wav-voices
      transformer:
        sampling_rate: 16000
        n_mels: 64
        win_length: 400
        hop_length: 512
        n_ffts: 1024
      type: CharacterDataset
    dev:
      json_path: /kaggle/working/common_voice/dev.json
      voice_path: /kaggle/working/common_voice/wav-voices
      transformer:
        sampling_rate: 16000
        n_mels: 64
        win_length: 400
        hop_length: 512
        n_ffts: 1024
      type: CharacterDataset
    test:
      json_path: /kaggle/working/common_voice/test.json
      voice_path: /kaggle/working/common_voice/wav-voices
      transformer:
        sampling_rate: 16000
        n_mels: 64
        win_length: 400
        hop_length: 512
        n_ffts: 1024
      type: CharacterDataset
    batch_size: 16
    workers: 4

vocab:
  type: CharacterVocab

training:
  checkpoint_path: saved_models
  learning_rate: 0.01
  use_amp: false
  weight_decay: 0.00005
  warmup: 1000
  score: CER
  patience: 20

model:
  name: ConFormer_character_CTC
  architecture: ConFormer
  device: cuda
  d_model: 144
  encoder:
    d_input: 80
    d_model: 128
    num_layers: 16
    conv_kernel_size: 31
    ffwd_residual_factor: 0.3
    ffwd_expansion_factor: 2
    num_heads: 4
    dropout: 0.1
  decoder:
    d_model: 256
    num_layers: 1

